# File 02/6

### DESCRIPTION:
For each sentence in the DataFrame:
- The main verb of a compound tense construction is identified and marked in   column `Is_Compound_Main`.
- Auxiliary verbs are assigned to their main verb via `Compound_Aux_Forms` and `Compound_Aux_IDs`
  (token IDs of the auxiliary verbs).
- Auxiliary verbs participating in compound tense constructions are marked in `Is_Compound_Aux`.

#### INPUT:
- ./OUTPUST/dataframe_02_5.csv
#### OUTPUT: 
- ./OUTPUTS/dataframe_02_6.csv

In [1]:
# third-party imports
import pandas as pd

In [2]:
# read input file 
csv_path="OUTPUTS/dataframe_02_5.csv"

df = pd.read_csv(
    csv_path,
    dtype={
        "Russian Translation": "string",
        "English Translation": "string"
    }
)

In [3]:
print(df.columns)

Index(['Unnamed: 0', 'File', 'Text Title', 'Language', 'Sentence ID',
       'Token ID', 'Form', 'Lemma', 'Lemma_norm', 'V_yva', 'V_nuti', 'V_COMB',
       'V_prefix', 'POS', 'Morphology', 'Head ID', 'Relation',
       'Presentation After', 'Russian Translation', 'English Translation',
       'Type', 'century', 'exact', 'lang', 'region', 'Negation',
       'Negation_Marker', 'place', 'Sentence_Text'],
      dtype='object')

In [4]:
def collect_aux_chain(start_id, group):
    forms, ids, lemmas, morphs = [], [], [], []
    visited = set()

    def dfs(head_id):
        for _, r in group.iterrows():
            if (
                pd.notna(r['Head ID']) and
                int(r['Head ID']) == head_id and
                r['Lemma'] == 'быти' and
                r['Relation'] == 'aux'
            ):
                aid = int(r['Token ID'])
                if aid in visited:
                    continue
                visited.add(aid)

                forms.append(r['Form'])
                ids.append(aid)
                lemmas.append(r['Lemma'])
                morphs.append(r['Morphology'])

                dfs(aid)

    dfs(start_id)
    return forms, ids, lemmas, morphs

In [5]:
def mark_compound_verbs(df: pd.DataFrame) -> pd.DataFrame:
    """
    For every sentence: mark those main verbs with an auxiliary verb (aux) 'byti'. 
    Add the following three new cols to the DataFrame to the MAIN VERB: 
    
      - 'Is_Compound_Main'    
          (True, if this token is the main verb as part of a compound verb)
          
      - 'Compound_Aux_Forms'  
          (List of all auxiliary forms of 'быти' that belong to the compound verb)
          
      - 'Compound_Aux_IDs'    
          (List of all Token-IDs of the auxiliaries of 'быти' found for the main verb)
    """
    df = df.copy()
    
    # Initialise new columns 
    ## with default boolean False  
    for col in ["Is_Compound_Main", "Is_Compound_Aux"]:
        df[col] = False

    ## with list columns (each row gets its own list)    
    for col in [
        "Compound_Aux_Forms",
        "Compound_Aux_IDs",
        "Compound_Aux_Lemmas",
        "Compound_Aux_Morphology"
    ]:
        df[col] = [[] for _ in range(len(df))]

    # group after sentence id -> so that the search will be done inside of the 
    # separate sentences 
    for sid, group in df.groupby('Sentence ID'):
        # 1) find all auxiliaries 'byti' (defined by properties: relation == "aux"; 
        # Lemma == 'быти' ('byti'), POS = "V-" )
        aux_byti = group.loc[
            (group['Lemma'] == 'быти') &
            (group['Relation'] == 'aux'),
            # For each entry: create a PANDAS DF containing the columns 'Token ID',
            # 'Form' and 'Head ID'
            ['Token ID', 'Form', 'Lemma',  'Morphology','Head ID']
        ]

        # mark auxiliary verbs of 'byti' in the DataFrame:
        # iterate over the Token IDs in the auxiliary DataFrame (aux_byti),
        # locate the corresponding rows in the main DataFrame (df),
        # and set 'Is_Compound_Aux' to True for those tokens
        for aux_tid in aux_byti['Token ID']:
            df.loc[df['Token ID'] == aux_tid, 'Is_Compound_Aux'] = True

        # 2) build two maps:
        # aux_map_forms:  main_verb_id -> list of auxiliary forms
        aux_map_forms = {}
        # aux_map_ids:    main_verb_id -> list of auxiliary verbs' token IDs
        aux_map_ids   = {}
        # aux_map_lemmas: lemma form of aux_map_forms
        aux_map_lemmas = {}
        # aux_map_morph:  morphology of aux_map_forms
        aux_map_morph = {}
        
        for _, row in aux_byti.iterrows():
            main_id      = int(row['Head ID'])    # the auxiliary verb's ID
            form_aux     = row['Form']            # e.g. 'ѥсмь' ("jesm'")
            lemma_aux    = row['Lemma']
            aux_token_id = int(row['Token ID'])   # e.g. 2157785
            morph_aux = row['Morphology']

            aux_map_forms.setdefault(main_id, []).append(form_aux)
            aux_map_lemmas.setdefault(main_id, []).append(lemma_aux)
            aux_map_ids.setdefault(main_id, []).append(aux_token_id)
            aux_map_morph.setdefault(main_id, []).append(morph_aux)


        # 3) mark the main verbs in aux_map_forms.keys()
        # 3) mark main verbs using recursive aux collection
        for _, row in group.iterrows():
            tid = int(row['Token ID'])
        
            #forms, ids, lemmas, morphs = collect_aux_chain(tid)
            forms, ids, lemmas, morphs = collect_aux_chain(tid, group)
        
            if forms:
                df.at[row.name, 'Is_Compound_Main'] = True
                df.at[row.name, 'Compound_Aux_Forms'] = forms
                df.at[row.name, 'Compound_Aux_IDs'] = ids
                df.at[row.name, 'Compound_Aux_Lemmas'] = lemmas
                df.at[row.name, 'Compound_Aux_Morphology'] = morphs
                
    return df


# function call: 
df = mark_compound_verbs(df)

In [6]:
def show_main_verbs_with_X_auxiliaries(auxiliary_count=1) -> pd.DataFrame:
    """
    Return all verbs that are marked as compound main verbs and have
    exactly `auxiliary_count` auxiliary forms.
    """
    df_sub = df.loc[
        (df['Is_Compound_Main']) &
        (df['Compound_Aux_Forms'].apply(len) == auxiliary_count),
        [
            "Form", "Sentence_Text",
            "Is_Compound_Main", "Is_Compound_Aux",
            "Compound_Aux_Forms", "Compound_Aux_IDs",
            "Compound_Aux_Lemmas", "Compound_Aux_Morphology"
        ]
    ]

    return df_sub    
# function call 
#df_sub = show_main_verbs_with_X_auxiliaries(auxiliary_count=1)
df_test = show_main_verbs_with_X_auxiliaries(1)

In [7]:
# check if columns were inserted as expected
df_test

,Form,Sentence_Text,Is_Compound_Main,Is_Compound_Aux,Compound_Aux_Forms,Compound_Aux_IDs,Compound_Aux_Lemmas,Compound_Aux_Morphology
11,повелѣлъ,"азъ ѥсмь повелѣлъ ѿдати бѹицѣ (и (съ, съ, съ))",True,False,[ѥсмь],[2157785],[быти],[1spia----i]
116,далъ,"ꙗ ѥсмь далъ блюдо (серебрьно, въ)",True,False,[ѥсмь],[2157889],[быти],[1spia----i]
127,велѣлъ,ѥсмь велѣлъ бити,True,False,[ѥсмь],[2157900],[быти],[1spia----i]
287,казалъ,мьстиславъ бѧшеть казалъ ѥже,True,False,[бѧшеть],[2305795],[быти],[3siia----i]
487,кѹпилъ,еси кѹпилъ робѹ,True,False,[еси],[2287510],[быти],[2spia----i]
...,...,...,...,...,...,...,...,...
234374,въпрошалъ,бѣ въпрошалъ,True,False,[бѣ],[2249798],[быти],[3siia----i]
234381,оумьрети,ми есть оумьрети,True,False,[есть],[2249807],[быти],[3spia----i]
234456,рекъли,волъстви бѧху рекъли оумрети,True,False,[бѧху],[2249883],[быти],[3piia----i]
234471,поставилъ,бѣхъ поставилъ егоже,True,False,[бѣхъ],[2249898],[быти],[1siia----i]
234479,оумерлъ,есть оумерлъ,True,False,[есть],[2249908],[быти],[3spia----i]

In [8]:
df.columns

Index(['Unnamed: 0', 'File', 'Text Title', 'Language', 'Sentence ID',
       'Token ID', 'Form', 'Lemma', 'Lemma_norm', 'V_yva', 'V_nuti', 'V_COMB',
       'V_prefix', 'POS', 'Morphology', 'Head ID', 'Relation',
       'Presentation After', 'Russian Translation', 'English Translation',
       'Type', 'century', 'exact', 'lang', 'region', 'Negation',
       'Negation_Marker', 'place', 'Sentence_Text', 'Is_Compound_Main',
       'Is_Compound_Aux', 'Compound_Aux_Forms', 'Compound_Aux_IDs',
       'Compound_Aux_Lemmas', 'Compound_Aux_Morphology'],
      dtype='object')

#### Assertions concerning the new columns

In [9]:
assert (
    df.loc[df["Is_Compound_Main"], "Compound_Aux_IDs"]
      .apply(lambda ids: len(ids) > 0)
      .all()
), "Some compound main verbs have no auxiliary IDs"

In [10]:
assert (
    df.loc[df["Is_Compound_Main"], "Compound_Aux_Forms"]
      .apply(lambda ids: len(ids) > 0)
      .all()
), "Some compound main verbs have no auxiliary forms"

In [11]:
# get an indexed series (True/False) for condition:
# list in col "Compound_Aux_IDs" is not empty
mask_has_aux = df["Compound_Aux_IDs"].apply(lambda ids: len(ids) > 0)

# assert for these entries: 
# elements in List of col "Compound_Aux_IDs" and col "Compound_Aux_Forms"
# have the same length 
assert (
    df.loc[mask_has_aux, ["Compound_Aux_IDs", "Compound_Aux_Forms"]]
      .apply(lambda row: len(row["Compound_Aux_IDs"]) == len(row["Compound_Aux_Forms"]), axis=1)
      .all()
), "Mismatch between number of auxiliary IDs and forms"

In [12]:
df.loc[mask_has_aux]

,Unnamed: 0,File,Text Title,Language,Sentence ID,Token ID,Form,Lemma,Lemma_norm,V_yva,...,Negation,Negation_Marker,place,Sentence_Text,Is_Compound_Main,Is_Compound_Aux,Compound_Aux_Forms,Compound_Aux_IDs,Compound_Aux_Lemmas,Compound_Aux_Morphology
11,11,mst,Mstislav’s letter,orv,189407,2157784,повелѣлъ,повелѣти,повелети,False,...,False,NaN,Novgorod,"азъ ѥсмь повелѣлъ ѿдати бѹицѣ (и (съ, съ, съ))",True,False,[ѥсмь],[2157785],[быти],[1spia----i]
116,116,mst,Mstislav’s letter,orv,189417,2157888,далъ,дати,дати,False,...,False,NaN,Novgorod,"ꙗ ѥсмь далъ блюдо (серебрьно, въ)",True,False,[ѥсмь],[2157889],[быти],[1spia----i]
127,127,mst,Mstislav’s letter,orv,189702,2157899,велѣлъ,велѣти,велети,False,...,False,NaN,Novgorod,ѥсмь велѣлъ бити,True,False,[ѥсмь],[2157900],[быти],[1spia----i]
287,287,mstislav-col,Colophon to Mstislav’s Gospel book,orv,213363,2305796,казалъ,казати,казати,False,...,False,NaN,Novgorod,мьстиславъ бѧшеть казалъ ѥже,True,False,[бѧшеть],[2305795],[быти],[3siia----i]
487,487,birchbark,109,orv,210149,2287509,кѹпилъ,купити,купити,False,...,False,NaN,Novgorod,еси кѹпилъ робѹ,True,False,[еси],[2287510],[быти],[2spia----i]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234374,234374,pvl-hyp,6420,orv,202882,2249801,въпрошалъ,въпрошати,в_прошати,False,...,False,NaN,Pskov,бѣ въпрошалъ,True,False,[бѣ],[2249798],[быти],[3siia----i]
234381,234381,pvl-hyp,6420,orv,202883,2249808,оумьрети,умрѣти,умрети,False,...,False,NaN,Pskov,ми есть оумьрети,True,False,[есть],[2249807],[быти],[3spia----i]
234456,234456,pvl-hyp,6420,orv,204114,2249884,рекъли,рещи,рещи,False,...,False,NaN,Pskov,волъстви бѧху рекъли оумрети,True,False,[бѧху],[2249883],[быти],[3piia----i]
234471,234471,pvl-hyp,6420,orv,202899,2249899,поставилъ,поставити,поставити,False,...,False,NaN,Pskov,бѣхъ поставилъ егоже,True,False,[бѣхъ],[2249898],[быти],[1siia----i]
234479,234479,pvl-hyp,6420,orv,204115,2249907,оумерлъ,умрѣти,умрети,False,...,False,NaN,Pskov,есть оумерлъ,True,False,[есть],[2249908],[быти],[3spia----i]

In [13]:
mask_has_aux.value_counts()

Compound_Aux_IDs
False    234166
True       1109
Name: count, dtype: int64

In [14]:
df[df["Is_Compound_Aux"].notna()].head(2)

,Unnamed: 0,File,Text Title,Language,Sentence ID,Token ID,Form,Lemma,Lemma_norm,V_yva,...,Negation,Negation_Marker,place,Sentence_Text,Is_Compound_Main,Is_Compound_Aux,Compound_Aux_Forms,Compound_Aux_IDs,Compound_Aux_Lemmas,Compound_Aux_Morphology
0,0,mst,Mstislav’s letter,orv,189407,2157773,Се,се,се,False,...,False,NaN,Novgorod,NaN,False,False,[],[],[],[]
1,1,mst,Mstislav’s letter,orv,189407,2157774,азъ,азъ,аз_,False,...,False,NaN,Novgorod,NaN,False,False,[],[],[],[]

In [15]:
df[df["Is_Compound_Aux"] == True].head(2)

,Unnamed: 0,File,Text Title,Language,Sentence ID,Token ID,Form,Lemma,Lemma_norm,V_yva,...,Negation,Negation_Marker,place,Sentence_Text,Is_Compound_Main,Is_Compound_Aux,Compound_Aux_Forms,Compound_Aux_IDs,Compound_Aux_Lemmas,Compound_Aux_Morphology
12,12,mst,Mstislav’s letter,orv,189407,2157785,ѥсмь,быти,быти,False,...,False,NaN,Novgorod,ѥсмь,False,True,[],[],[],[]
117,117,mst,Mstislav’s letter,orv,189417,2157889,ѥсмь,быти,быти,False,...,False,NaN,Novgorod,ѥсмь,False,True,[],[],[],[]

#### Write pandas DataFrame to csv

In [16]:
df.to_csv("./OUTPUTS/dataframe_02_6.csv")